server:
  port: 9055
  context-path: /spider-images

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/extend/*.xml

spring:
  application:
    name: spider-images
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spider?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 200
      max-idle: 100
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      jdbc-interceptors: ConnectionState;


# \u65E5\u5FD7\u4F4D\u7F6E
logging:
  path: /data1/logs/${spring.application.name}